config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:show]
  resources :media_items
  resources :rooms
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/media_item.rb
class MediaItem < ApplicationRecord
  belongs_to :room
  has_one_attached :item
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_action :set_media_item, only: %i[ show edit update destroy ]

  # GET /media_items or /media_items.json
  def index
    @media_items = MediaItem.all
  end

  # GET /media_items/1 or /media_items/1.json
  def show
  end

  # GET /media_items/new
  def new
    @media_item = MediaItem.new
  end

  # GET /media_items/1/edit
  def edit
  end

  # POST /media_items or /media_items.json
  def create
    @media_item = MediaItem.new(media_item_params)

    respond_to do |format|
      if @media_item.save
        format.html { redirect_to media_item_url(@media_item), notice: "Media item was successfully created." }
        format.json { render :show, status: :created, location: @media_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @media_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_items/1 or /media_items/1.json
  def update
    respond_to do |format|
      if @media_item.update(media_item_params)
        format.html { redirect_to media_item_url(@media_item), notice: "Media item was successfully updated." }
        format.json { render :show, status: :ok, location: @media_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @media_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_items/1 or /media_items/1.json
  def destroy
    @media_item.destroy!

    respond_to do |format|
      format.html { redirect_to media_items_url, notice: "Media item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_item
      @media_item = MediaItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def media_item_params
      params.require(:media_item).permit(:x, :y, :z, :item, :room_id)
    end
end

app/helpers/media_items_helper.rb
module MediaItemsHelper
end

app/views/media_items/_form.html.erb
<%= form_with(model: media_item) do |form| %>
  <% if media_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(media_item.errors.count, "error") %> prohibited this media_item from being saved:</h2>

      <ul>
        <% media_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :y, style: "display: block" %>
    <%= form.text_field :y %>
  </div>

  <div>
    <%= form.label :z, style: "display: block" %>
    <%= form.text_field :z %>
  </div>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.file_field :item %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.text_field :room_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/media_items/_media_item.html.erb
<div id="<%= dom_id media_item %>">
  <p>
    <strong>X:</strong>
    <%= media_item.x %>
  </p>

  <p>
    <strong>Y:</strong>
    <%= media_item.y %>
  </p>

  <p>
    <strong>Z:</strong>
    <%= media_item.z %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= link_to media_item.item.filename, media_item.item if media_item.item.attached? %>
    <%= image_tag media_item.item if media_item.item.attached? %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= media_item.room_id %>
  </p>

</div>

app/views/media_items/edit.html.erb
<h1>Editing media item</h1>

<%= render "form", media_item: @media_item %>

<br>

<div>
  <%= link_to "Show this media item", @media_item %> |
  <%= link_to "Back to media items", media_items_path %>
</div>

app/views/media_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Media items</h1>

<div id="media_items">
  <% @media_items.each do |media_item| %>
    <%= render media_item %>
    <p>
      <%= link_to "Show this media item", media_item %>
    </p>
  <% end %>
</div>

<%= link_to "New media item", new_media_item_path %>

app/views/media_items/new.html.erb
<h1>New media item</h1>

<%= render "form", media_item: @media_item %>

<br>

<div>
  <%= link_to "Back to media items", media_items_path %>
</div>

app/views/media_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @media_item %>

<div>
  <%= link_to "Edit this media item", edit_media_item_path(@media_item) %> |
  <%= link_to "Back to media items", media_items_path %>

  <%= button_to "Destroy this media item", @media_item, method: :delete %>
</div>