config/routes.rb
Rails.application.routes.draw do
  resources :profiles, only: [:show]
  resources :media_items
  resources :rooms
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roomagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>
    <header class="site-header">
      <div class="left-items">
        <%= link_to "Roomagram", root_path, class: "logo" %>
      </div>
      <div class="right-items">
        <% if Current.user.present? %>
          <nav>
            <ul>
              <li>
                <%= link_to "My rooms", rooms_path %>
              </li>
            </ul>
          </nav>
        <% end %>
        <% if Current.user.present? %>
          <div>Signed as <%= Current.user.name %></div>

          <%= button_to "Log out", Current.session, method: :delete %>
        <% else %>
            <%= link_to "Sign in", sign_in_path %>        
        <% end %>
      </div>
      
    </header>
    <%= yield %>
  </body>
</html>